package me.agohar.usersec.security.config;

import me.agohar.usersec.security.test.util.JwtTestTokenGenerator;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;

/**
 * Local JWT configuration for testing with local tokens
 * This configuration provides a JWT decoder that can validate tokens
 * generated by JwtTestTokenGenerator
 */
@Configuration
@Profile("local-test")
public class LocalJwtConfig {

    @Bean
    public JwtDecoder jwtDecoder() {
        // Use the same secret key as the token generator
        return NimbusJwtDecoder.withSecretKey(JwtTestTokenGenerator.getSecretKey()).build();
    }
}
